server.port=${SERVER_PORT}

frontend.url=${FRONTEND_URL}

spring.jpa.hibernate.ddl-auto=update

#spring.application.name=Online-Food-Ordering
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

#com.mysql.cj.jdbc.Driver , without .cj its throwing error

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

stripe.api.key=${STRIPE_API_KEY}